### ISSUE TITLE
アソシエーションを活用してモデルの関連付けを行う

### ISSUE THREAD

**Issue by norotime** [kakerukaneko/quiz_app#12]
@kakerukaneko アソシエーションを知らないとRailsエンジニアとして採用されないと思います。必ず使えるようになりましょう。

https://railsguides.jp/association_basics.html#%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B%E7%90%86%E7%94%B1

LikeとUser
LikeとPost
QuizとGenre
ResultとQuiz

採用担当者は、関連付けがされていないモデルを見ると、力不足を感じてしまうかもしれません。

**Comment by kakerukaneko** [comment]
@norotime 
Likeは投稿された問題にいいね機能が付けれたらと思い、modelsを作成しました。
Postは作成しておらず、今の所、投稿した問題はQuizの方に追加されます。
識別方法はquiz_addIdというのがあるのですが、そこで識別しています。
